//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestFlightSearch.Solution.infraeroConsultaVoos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="infraeroConsultaVoos.IConsultaVoos")]
    public interface IConsultaVoos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVoosSentido", ReplyAction="http://tempuri.org/IConsultaVoos/ConsultarVoosSentidoResponse")]
        string ConsultarVoosSentido(string icao, string idioma, bool partida, bool exibirFinalizados, int registrosPagina, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVoosSentido", ReplyAction="http://tempuri.org/IConsultaVoos/ConsultarVoosSentidoResponse")]
        System.Threading.Tasks.Task<string> ConsultarVoosSentidoAsync(string icao, string idioma, bool partida, bool exibirFinalizados, int registrosPagina, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVoosCiaAerea", ReplyAction="http://tempuri.org/IConsultaVoos/ConsultarVoosCiaAereaResponse")]
        string ConsultarVoosCiaAerea(string icao, string idioma, bool partida, string siglaCiaAerea, bool exibirFinalizados, int registrosPagina, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVoosCiaAerea", ReplyAction="http://tempuri.org/IConsultaVoos/ConsultarVoosCiaAereaResponse")]
        System.Threading.Tasks.Task<string> ConsultarVoosCiaAereaAsync(string icao, string idioma, bool partida, string siglaCiaAerea, bool exibirFinalizados, int registrosPagina, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVoosNumero", ReplyAction="http://tempuri.org/IConsultaVoos/ConsultarVoosNumeroResponse")]
        string ConsultarVoosNumero(string icao, string idioma, bool partida, string numeroVoo, bool exibirFinalizados, int registrosPagina, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarVoosNumero", ReplyAction="http://tempuri.org/IConsultaVoos/ConsultarVoosNumeroResponse")]
        System.Threading.Tasks.Task<string> ConsultarVoosNumeroAsync(string icao, string idioma, bool partida, string numeroVoo, bool exibirFinalizados, int registrosPagina, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAeroportos", ReplyAction="http://tempuri.org/IConsultaVoos/ListarAeroportosResponse")]
        string ListarAeroportos(string idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAeroportos", ReplyAction="http://tempuri.org/IConsultaVoos/ListarAeroportosResponse")]
        System.Threading.Tasks.Task<string> ListarAeroportosAsync(string idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCompanhias", ReplyAction="http://tempuri.org/IConsultaVoos/ListarCompanhiasResponse")]
        string ListarCompanhias(string icao, string idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCompanhias", ReplyAction="http://tempuri.org/IConsultaVoos/ListarCompanhiasResponse")]
        System.Threading.Tasks.Task<string> ListarCompanhiasAsync(string icao, string idioma);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultaVoosChannel : BestFlightSearch.Solution.infraeroConsultaVoos.IConsultaVoos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaVoosClient : System.ServiceModel.ClientBase<BestFlightSearch.Solution.infraeroConsultaVoos.IConsultaVoos>, BestFlightSearch.Solution.infraeroConsultaVoos.IConsultaVoos {
        
        public ConsultaVoosClient() {
        }
        
        public ConsultaVoosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaVoosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaVoosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaVoosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConsultarVoosSentido(string icao, string idioma, bool partida, bool exibirFinalizados, int registrosPagina, int pagina) {
            return base.Channel.ConsultarVoosSentido(icao, idioma, partida, exibirFinalizados, registrosPagina, pagina);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarVoosSentidoAsync(string icao, string idioma, bool partida, bool exibirFinalizados, int registrosPagina, int pagina) {
            return base.Channel.ConsultarVoosSentidoAsync(icao, idioma, partida, exibirFinalizados, registrosPagina, pagina);
        }
        
        public string ConsultarVoosCiaAerea(string icao, string idioma, bool partida, string siglaCiaAerea, bool exibirFinalizados, int registrosPagina, int pagina) {
            return base.Channel.ConsultarVoosCiaAerea(icao, idioma, partida, siglaCiaAerea, exibirFinalizados, registrosPagina, pagina);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarVoosCiaAereaAsync(string icao, string idioma, bool partida, string siglaCiaAerea, bool exibirFinalizados, int registrosPagina, int pagina) {
            return base.Channel.ConsultarVoosCiaAereaAsync(icao, idioma, partida, siglaCiaAerea, exibirFinalizados, registrosPagina, pagina);
        }
        
        public string ConsultarVoosNumero(string icao, string idioma, bool partida, string numeroVoo, bool exibirFinalizados, int registrosPagina, int pagina) {
            return base.Channel.ConsultarVoosNumero(icao, idioma, partida, numeroVoo, exibirFinalizados, registrosPagina, pagina);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarVoosNumeroAsync(string icao, string idioma, bool partida, string numeroVoo, bool exibirFinalizados, int registrosPagina, int pagina) {
            return base.Channel.ConsultarVoosNumeroAsync(icao, idioma, partida, numeroVoo, exibirFinalizados, registrosPagina, pagina);
        }
        
        public string ListarAeroportos(string idioma) {
            return base.Channel.ListarAeroportos(idioma);
        }
        
        public System.Threading.Tasks.Task<string> ListarAeroportosAsync(string idioma) {
            return base.Channel.ListarAeroportosAsync(idioma);
        }
        
        public string ListarCompanhias(string icao, string idioma) {
            return base.Channel.ListarCompanhias(icao, idioma);
        }
        
        public System.Threading.Tasks.Task<string> ListarCompanhiasAsync(string icao, string idioma) {
            return base.Channel.ListarCompanhiasAsync(icao, idioma);
        }
    }
}
